apiVersion: ansible.cloudbending.dev/v1beta1
kind: PlaybookPlan
metadata:
  name: chroot-example
spec:
  image: docker.io/serversideup/ansible-core:2.18
  # schedule: "*/2 * * * *"
  timeZone: Europe/Berlin
  connectionStrategy:
    chroot:
      tolerations:
        - key: CriticalAddonsOnly
          effect: NoExecute
          operator: Exists
  inventory:
    - name: nodes
      hosts:
        fromNodes:
          matchLabels:
            node.kubernetes.io/instance-type: k3s
  template:
    requirements: |
      collections:
        - name: community.general
          version: ">=6.0.0"
    playbook: |
      - hosts: all

        tasks:
          - name: Ensure test file exists
            ansible.builtin.copy:
              dest: /var/home/admin/a-file
              owner: admin
              group: admin
              mode: "0640"
              content: |
                Hello, world!
