# code: language=yaml
apiVersion: ansible.cloudbending.dev/v1alpha1
kind: PlaybookPlan
metadata:
  name: blubb
spec:
  # An OCI image with Ansible and all required collections
  image: docker.io/serversideup/ansible-core:2.18
  # Controls when a playbook is executed
  triggers:
    # The playbook will run immediately after the resource is created or updated ...
    immediate: false
    # ... and daily at 1 AM
    schedule: "0 1 * * *"
  # These host groups will be available in our playbook
  inventory:
    - name: linux
      hosts:
        fromNodes:
          matchLabels:
            kubernetes.io/os: linux
    - name: controlplane
      hosts:
        fromNodes:
          matchLabels:
            node-role.kubernetes.io/control-plane: "true"
  # Used to decide on a connection plugin. We will always create one Ansible (cron)job per host.
  executionStrategy:
    chroot:
  # These will usually be populated via Helm
  variables:
    inline:
      # Variables will be available in Ansible
      ttyTimeout:
        present: true
  # The playbook will be built from this, some fields will be set automatically (vars, hosts)
  templates:
    - hosts: mo-clients
      tasks: |
        - name: Ensure script for setting timeout for inactive TTY users is present
          when: "ttyTimeout.present"
          ansible.builtin.copy:
            src: set-tty-timeout.sh
            dest: /etc/profile.d/set-tty-timeout.sh
            owner: root
            group: root
            mode: "0644"

        - name: Ensure script for setting timeout for inactive TTY users is absent
          when: "not ttyTimeout.present"
          ansible.builtin.file:
            state: absent
          path: /etc/profile.d/set-tty-timeout.sh

# status:
# conditions:
#   - lastTransitionTime: 2025-06-04T22:24:00+02:00
#     type: LastExecutionSuccessful
#     status: "False"
#     reason: Waiting
#     message: Playbook is waiting for an execution trigger
# eligibleHosts:
#   controlplane:
#     - homelab-control-0
#   workers:
#     - homelab-worker-0
#     - homelab-worker-1
# eligibleHostsCount: 3
# phase: Waiting
