apiVersion: ansible.cloudbending.dev/v1beta1
kind: PlaybookPlan
metadata:
  name: ccu-example
spec:
  image: docker.io/serversideup/ansible-core:2.18
  inventory:
    - name: ccu
      hosts:
        fromList:
          - ccu.fritz.box
  connectionStrategy:
    ssh:
      user: root
      secretRef:
        name: ssh
  template:
    playbook: |
      - hosts: all
        tasks:
          - name: Copy certificate
            ansible.builtin.copy:
              src: tls.crt
              dest: /etc/somewhere/tls.crt
              owner: root
              group: root
              mode: "0640"
