apiVersion: ansible.cloudbending.dev/v1beta1
kind: StaticInventory
metadata:
  name: oneshot-fail
spec:
  hosts:
    - name: all
      hosts:
        - homelab-worker-0
        - homelab-worker-1
---
apiVersion: ansible.cloudbending.dev/v1beta1
kind: PlaybookPlan
metadata:
  name: oneshot-fail
spec:
  image: docker.io/serversideup/ansible-core:2.18
  schedule: "* * * * *"
  timeZone: Europe/Berlin
  connectionStrategy:
    chroot: {}
  inventoryRefs:
    - staticInventory: oneshot-fail
  template:
    requirements: |
      collections:
        - name: community.general
          version: ">=6.0.0"
    playbook: |
      - hosts: all

        tasks:
          - name: Fail
            ansible.builtin.fail:
              msg: This is supposed to fail.
